/*
 * Copyright (c) 2011-2013 Konnibe
 * Copyright (c) 2013-2015 Del Edson
 * Copyright (c) 2015-2021 Peter Tulp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Autogenerated by png2wx.pl on Thu Nov  4 13:06:52 2010 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images( void );

extern wxBitmap *_img_logbook_pi;
extern wxBitmap *_img_logbook;
extern const wxBitmap *_img_Bullet_green;
extern const wxBitmap *_img_Bullet_red;
extern const wxBitmap *_img_Bullet_yellow;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_logbookkonni;
extern wxString _svg_logbookkonni_rollover;
extern wxString _svg_logbookkonni_toggled;
#endif


#endif /* ICONS_H */
